export const FLOW_STEPS = Object.freeze({
  ASK_URL: 'ASK_URL',
  ASK_OUTPUT_LENGTH: 'ASK_OUTPUT_LENGTH',
  ASK_OUTPUT_LENGTH_CUSTOM: 'ASK_OUTPUT_LENGTH_CUSTOM',
  ASK_OUTPUT_MODE: 'ASK_OUTPUT_MODE',
  CONFIRM: 'CONFIRM',
  EDIT_MENU: 'EDIT_MENU'
});
