export const FLOW_STEPS = Object.freeze({
  ASK_URL: 'ASK_URL',
  ASK_OUTPUT_MODE: 'ASK_OUTPUT_MODE',
  ASK_SINGLE_LENGTH: 'ASK_SINGLE_LENGTH',
  ASK_SINGLE_LENGTH_CUSTOM: 'ASK_SINGLE_LENGTH_CUSTOM',
  ASK_VARIANT_DURATION_MODE: 'ASK_VARIANT_DURATION_MODE',
  ASK_VARIANT_DURATIONS_CUSTOM: 'ASK_VARIANT_DURATIONS_CUSTOM',
  CONFIRM: 'CONFIRM',
  EDIT_MENU: 'EDIT_MENU'
});
